---
title: "p8105_hw5_cg3112"
output: github_document
---

```{r setup, include=FALSE}
library(tidyr)
library(dplyr)
library(p8105.datasets)
library(tidyverse)
```


## Problem 1
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))



input_missing <- function(x) {
  if(is.character(x)) {
    x[is.na(x)] <- "Virginica"
    return(x)
  }
  else if (is.numeric(x)) {
    x[is.na(x)] <- mean(x, na.rm = TRUE)
    return(x)
  }
}

iris_filled <-  map(.x = iris_with_missing, ~ input_missing(.x)) %>% as.data.frame()

```

## Problem 2
```{r}
setwd("./p2")

working <- list.files()
 
p2 <- map(working, read_csv) %>%
  bind_rows() %>%
  mutate(
    name = working
  ) %>%
  separate(name, c("subject", "arm"), sep = "_") %>%
    pivot_longer(
      week_1:week_8,
               names_to = "week",
               values_to = "values"
      ) %>%
  mutate(
    arm = str_remove(arm, ".csv"),
    arm = as.numeric(arm),
    week = str_remove(week, "week_"),
    week = as.factor(week)
  )


plots <- p2 %>% select(subject, arm, week, values ) %>%
  ggplot(aes(x = week, y = values, group=interaction(subject,arm), color = arm)) +
  geom_line() + 
  geom_point() 

plots  
```

## Problem 3
```{r}



sim_regression = function(n, beta0 = 2, beta1 = 0) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1*x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data) %>% broom::tidy() %>%
  filter(term == "x") %>%
  select(estimate,p.value)

}

#output = vector("list", 10000)

#for (i in 1:10000) {
#  output[[i]] = sim_regression(30)
#} 

sim_results = rerun(10000, sim_regression(30, 2, 0)) %>%
  bind_rows()

#Now to run with different beta1s




```

